/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

fun main() {
    println("Arctg(0) = ${ArctanKt.arctg(0.0)}")
    println("Arctg(1) = ${ArctanKt.arctg(1.0)}")
    println("Arctg(-1) = ${ArctanKt.arctg(-1.0)}")
    println("Arctg(0.5) = ${ArctanKt.arctg(0.5)}")
}
